######################## default configuration ####################
baseURL = "http://examplesite.org/"
title = "ValetBot"
theme = "bigspring-hugo-instance"
# post pagination
paginate = "3"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# google analytics
googleAnalytics = "" # example : UA-123-45

[params]
favicon = "favicon.ico"
# unsafe html
[markup.goldmark.renderer]
unsafe = true